[project]
name = "umap-autoencoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "numpy>=2.0.2",
    "torch>=2.8.0",
    "umap-learn>=0.5.9.post2",
]
